name: "Deploy to firebase"
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      
      - name: Install dependencies
        working-directory: ./backend
        run: npm install
      
      - name: Test
        run: npm test
        working-directory: ./backend

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
